name: paralelo
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  #...
  flutter_localizations:
    sdk: flutter
  #...
  andorasoft_flutter:
    path: ../../Andorasoft-Flutter
  #...
  easy_localization: ^3.0.8
  #...
  flutter_tabler_icons: ^1.43.0
  #...
  flutter_riverpod: ^2.4.0
  #...
  flutter_dotenv: ^5.1.0
  #...
  flutter_svg: ^2.2.0
  #...
  flutter_rating_bar: ^4.0.1
  #...
  shared_preferences: ^2.5.3
  #...
  app_settings: ^6.1.1
  #...
  permission_handler: ^12.0.1
  #...
  firebase_core: ^4.1.1
  #...
  firebase_messaging: ^16.0.2
  #...
  cloud_firestore: ^6.0.2
  #...
  supabase_flutter: ^2.9.1
  #...
  lucide_icons: ^0.257.0
  #...
  easy_debounce: ^2.0.3
  #...
  go_router: ^16.0.0
  #...
  timeago: ^3.7.1
  #...
  uuid: ^4.5.1
  #...
  intl: ^0.20.2
  #...
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #...
  assets:
    - assets/translations/
    - assets/images/
    - .env
