// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuEn7b8VoojxcEWq9BPc-3gRbG_i0UUlE',
    appId: '1:91360332225:android:6b84499ff35c750d5d4740',
    messagingSenderId: '91360332225',
    projectId: 'andorasoft-paralelo',
    storageBucket: 'andorasoft-paralelo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHt0NVYjpDXjtSG5-QrEfAZCz3tu_LM2c',
    appId: '1:91360332225:ios:7bda2bb2750c84235d4740',
    messagingSenderId: '91360332225',
    projectId: 'andorasoft-paralelo',
    storageBucket: 'andorasoft-paralelo.firebasestorage.app',
    iosBundleId: 'com.andorasoft.paralelo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDGLa1-DhrBw5IFqwRfNvbj8ap_7TIHRLw",
    authDomain: "andorasoft-paralelo.firebaseapp.com",
    projectId: "andorasoft-paralelo",
    storageBucket: "andorasoft-paralelo.firebasestorage.app",
    messagingSenderId: "91360332225",
    appId: "1:91360332225:web:7dea217a2b0a878e5d4740",
  );
}
