-- ============================================================
-- INSERT DEFAULT SKILLS
-- ============================================================
insert into
  "public"."skill" (name)
values
  ('Redacción académica'),
  ('Revisión de literatura'),
  ('Metodología de investigación'),
  ('Análisis de datos'),
  ('SPSS'),
  ('Programación en R'),
  ('Elaboración de informes científicos'),
  ('Pruebas de hipótesis'),
  ('Diseño de encuestas'),
  ('Normas APA'),
  ('Documentación técnica'),
  ('Asesoría de tesis'),
  ('Modelado estadístico'),
  ('Visualización de datos'),
  ('Corrección de textos académicos'),
  ('HTML'),
  ('CSS'),
  ('JavaScript'),
  ('TypeScript'),
  ('React'),
  ('Vue.js'),
  ('Svelte'),
  ('Node.js'),
  ('Express.js'),
  ('Python'),
  ('Django'),
  ('Flask'),
  ('Java'),
  ('Kotlin'),
  ('C++'),
  ('C#'),
  ('Dart'),
  ('Flutter'),
  ('Swift'),
  ('PHP'),
  ('Laravel'),
  ('Go'),
  ('Rust'),
  ('GraphQL'),
  ('Diseño de API REST'),
  ('Git / GitHub'),
  ('Linux / CLI'),
  ('Docker'),
  ('Kubernetes'),
  ('Supabase'),
  ('Firebase'),
  ('PostgreSQL'),
  ('MySQL'),
  ('SQLite'),
  ('MongoDB'),
  ('Redis'),
  ('Despliegue en la nube'),
  ('CI/CD'),
  ('Pruebas de software'),
  ('Automatización QA'),
  ('Diseño gráfico'),
  ('Diseño UX/UI'),
  ('Figma'),
  ('Adobe Photoshop'),
  ('Adobe Illustrator'),
  ('Adobe After Effects'),
  ('Adobe Premiere'),
  ('Blender'),
  ('Canva'),
  ('InDesign'),
  ('Tipografía'),
  ('Diseño de logotipos'),
  ('Branding'),
  ('Diseño editorial'),
  ('Modelado 3D'),
  ('Animación 2D / 3D'),
  ('Edición de video'),
  ('Fotografía'),
  ('Retoque digital'),
  ('Teoría del color'),
  ('Marketing digital'),
  ('SEO'),
  ('SEM'),
  ('Google Analytics'),
  ('Google Ads'),
  ('Facebook Ads'),
  ('Copywriting'),
  ('Estrategia de contenido'),
  ('Gestión de redes sociales'),
  ('Email marketing'),
  ('Community management'),
  ('Estrategia de marca'),
  ('Automatización de marketing'),
  ('Marketing de influencers'),
  ('Relaciones públicas'),
  ('Storytelling'),
  ('Diseño de campañas publicitarias'),
  ('Optimización de e-commerce'),
  ('Gestión de proyectos'),
  ('Plan de negocios'),
  ('Presupuestación'),
  ('Análisis financiero'),
  ('Gestión de riesgos'),
  ('Lean Startup'),
  ('Agile / Scrum'),
  ('Gestión de producto'),
  ('Investigación de mercado'),
  ('Planeación estratégica'),
  ('Negociación'),
  ('Liderazgo'),
  ('Coordinación de equipos'),
  ('Atención al cliente'),
  ('Emprendimiento'),
  ('Diseño de pitch decks'),
  ('Evaluación de impacto ambiental'),
  ('Auditoría ambiental'),
  ('Gestión de residuos'),
  ('Análisis de calidad de agua'),
  ('Control de contaminación atmosférica'),
  ('Legislación ambiental'),
  ('Desarrollo sostenible'),
  ('Educación ambiental'),
  ('Cartografía SIG'),
  ('QGIS'),
  ('ArcGIS'),
  ('Teledetección'),
  ('Análisis de uso de suelo'),
  ('Modelación hidrológica'),
  ('Modelación de infiltración'),
  ('Muestreo de suelos'),
  ('Cálculo de huella de carbono'),
  ('Energías renovables'),
  ('Monitoreo ecológico'),
  ('Indicadores ambientales'),
  ('AutoCAD'),
  ('Revit'),
  ('SolidWorks'),
  ('MATLAB'),
  ('Simulink'),
  ('ANSYS'),
  ('CATIA'),
  ('Programación PLC'),
  ('Diseño de circuitos eléctricos'),
  ('Diseño mecánico'),
  ('Análisis estructural'),
  ('Termodinámica'),
  ('Mecánica de fluidos'),
  ('Simulación de procesos'),
  ('Control de procesos químicos'),
  ('Instrumentación'),
  ('Sistemas SCADA'),
  ('Civil 3D'),
  ('Levantamientos topográficos'),
  ('Técnicas de enseñanza'),
  ('Planificación de clases'),
  ('Tecnologías educativas'),
  ('Moodle / Google Classroom'),
  ('Evaluación del aprendizaje'),
  ('Comunicación efectiva'),
  ('Orientación académica'),
  ('Facilitación de grupos'),
  ('Diseño curricular'),
  ('Oratoria'),
  ('Gestión del tiempo'),
  ('Inglés avanzado'),
  ('Francés intermedio'),
  ('Alemán intermedio'),
  ('Portugués intermedio'),
  ('Español nativo'),
  ('Traducción académica'),
  ('Traducción técnica'),
  ('Corrección gramatical'),
  ('Revisión lingüística'),
  ('Redacción creativa'),
  ('Design Thinking'),
  ('Ideación de proyectos'),
  ('Prototipado rápido'),
  ('Lean Canvas'),
  ('Validación de modelo de negocio'),
  ('Investigación de usuarios'),
  ('Pruebas de usabilidad'),
  ('Presentación de proyectos'),
  ('Validación de mercado'),
  ('Estrategia de crowdfunding'),
  ('Pensamiento crítico'),
  ('Resolución de problemas'),
  ('Adaptabilidad'),
  ('Trabajo en equipo'),
  ('Comunicación'),
  ('Liderazgo'),
  ('Organización'),
  ('Creatividad'),
  ('Iniciativa'),
  ('Análisis lógico'),
  ('Responsabilidad'),
  ('Ética profesional');